export const GET_USER = 'GET_USER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const SET_SCHOOL_TYPE = 'SET_SCHOOL_TYPE';
export const SET_GROUPS_COUNT = 'SET_GROUPS_COUNT';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const REMOVE_SUBJECT = 'REMOVE_SUBJECT';
export const ADD_TIMESLOT = 'ADD_TIMESLOT';
export const REMOVE_TIMESLOT = 'REMOVE_TIMESLOT';
export const GENERATE_GROUPS_STARTED = 'GENERATE_GROUPS_STARTED';
export const GENERATE_GROUPS_FINISHED = 'GENERATE_GROUPS_FINISHED';
export const ADD_SUBJECT_TO_GROUP = 'ADD_SUBJECT_TO_GROUP';
export const REMOVE_SUBJECT_FROM_GROUP = 'REMOVE_SUBJECT_FROM_GROUP';
export const FINISH_WIZARD = 'FINISH_WIZARD';

export const SET_TITLE = 'SET_TITLE';
export const RESET_MESSAGE = 'RESET_MESSAGE';
