export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_STUDENT_REQUEST = 'REGISTER_STUDENT_REQUEST';
export const REGISTER_STUDENT_SUCCESS = 'REGISTER_STUDENT_SUCCESS';
export const REGISTER_STUDENT_FAILURE = 'REGISTER_STUDENT_FAILURE';

export const REGISTER_TEACHER_REQUEST = 'REGISTER_TEACHER_REQUEST';
export const REGISTER_TEACHER_SUCCESS = 'REGISTER_TEACHER_SUCCESS';
export const REGISTER_TEACHER_FAILURE = 'REGISTER_TEACHER_FAILURE';

export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
