export const CHECK_SETUP_SUCCESS = 'CHECK_SETUP_SUCCESS';
export const RESET_SETUP_SUCCESS = 'RESET_SETUP_SUCCESS';

export const FETCH_FREE_SUBJECTS_SUCCESS = 'FETCH_FREE_SUBJECTS_SUCCESS';
export const FETCH_TEACHERS_COUNT_SUCCESS = 'FETCH_TEACHERS_COUNT_SUCCESS';
export const FETCH_STUDENTS_COUNT_SUCCESS = 'FETCH_STUDENTS_COUNT_SUCCESS';
export const FETCH_GROUPS_COUNT_SUCCESS = 'FETCH_GROUPS_COUNT_SUCCESS';
export const FETCH_SUBJECTS_COUNT_SUCCESS = 'FETCH_SUBJECTS_COUNT_SUCCESS';
