export const GENERATE_TIMETABLE_SUCCESS = 'GENERATE_TIMETABLE_SUCCESS';

export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS';
export const FETCH_TIMESLOTS_SUCCESS = 'FETCH_TIMESLOTS_SUCCESS';
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';

export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
